// Issue metadata — migrated from _config.yml collections block
module.exports = {
  issue01: {
    slug: "issue01",
    slug_fr: "fr/issue01",
    slug_es: "es/issue01",
    number: 1,
    date: "June 2016",
    title: "Issue (1)",
    editors: ["Kaiama Glover", "Alex Gil", "Kelly Baker Josephs"],
    production: ["Alex Gil", "Dennis Tenen", "Brian Ballsun-Stanton", "Kelly S. Martin"],
  },
  issue02: {
    slug: "issue02",
    slug_fr: "fr/issue02",
    slug_es: "es/issue02",
    number: 2,
    date: "September 2017",
    title: "Issue (2)",
    editors: ["Kaiama Glover", "Alex Gil"],
    production: ["Alex Gil", "Brian Ballsun-Stanton", "Kelly S. Martin"],
  },
  issue03: {
    slug: "issue03",
    slug_fr: "fr/issue03",
    slug_es: "es/issue03",
    number: 3,
    date: "April 2019",
    title: "Issue (3)",
    editors: ["Kaiama Glover", "Alex Gil", "Jessica Marie Johnson"],
    production: ["Alex Gil", "Brian Ballsun-Stanton", "Kelly S. Martin"],
    interactives: [
      {
        title: ".break .dance",
        author: ["Marisa Parham"],
        url: "/issue03/parham/parham.html",
        pdf: false,
      },
      {
        title: "Breaking, Dancing, Making in the Machine: Notes on \".break .dance\"",
        author: ["Marisa Parham"],
        url: "/issue03/parham-process/parham-process.html",
        pdf: false,
      },
    ],
  },
  issue04: {
    slug: "issue04",
    slug_fr: "fr/issue04",
    slug_es: "es/issue04",
    number: 4,
    date: "February 2020",
    title: "Issue (4)",
    editors: ["Kaiama Glover", "Alex Gil"],
    production: ["Alex Gil"],
  },
  issue05: {
    slug: "issue05",
    slug_fr: "fr/issue05",
    slug_es: "es/issue05",
    number: 5,
    date: "December 2020",
    title: "Issue (5)",
    editors: ["Kaiama Glover", "Alex Gil"],
    production: ["Alex Gil"],
  },
  issue06: {
    slug: "issue06",
    slug_fr: "fr/issue06",
    slug_es: "es/issue06",
    number: 6,
    date: "May 2022",
    title: "Issue (6)",
    editors: ["Kaiama Glover", "Alex Gil"],
    production: ["Alex Gil"],
  },
  issue07: {
    slug: "issue07",
    slug_fr: "fr/issue07",
    slug_es: "es/issue07",
    number: 7,
    date: "May 2023",
    title: "Issue (7)",
    editors: ["Kaiama Glover", "Alex Gil"],
    production: ["Alex Gil"],
  },
  issue08: {
    slug: "issue08",
    slug_fr: "fr/issue08",
    slug_es: "es/issue08",
    number: 8,
    date: "April 2025",
    title: "Issue (8)",
    editors: ["Kaiama Glover", "Alex Gil"],
    production: ["Alex Gil"],
  },
};
